### ISSUE TITLE
Can not run metrics-fluentd-monitor-agent plugin

### ISSUE THREAD

**Issue by hoalequang** [sensu-plugins/sensu-plugins-fluentd#7] opened 2016-10-12 11:44 UTC
Hi team,
When I use this plugin, I see a problem with : 
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-fluentd-0.1.0/bin/metrics-fluentd-monitor-agent.rb:60:in `run': Object#timeout is deprecated, use Timeout.timeout instead.

and I did not see the metrics-fluentd-monitor-agent.
I ran command : **sensu-install -p fluentd** to install this plugin

Please help me to resolve this issue!! Thanks

**Comment by eheydrick** [comment] 2017-05-15 05:05
I updated the `timeout` methods in PR #8 to remove the deprecation warnings. As for not seeing metrics-fluentd-monitor-agent the issue is the plugin hasn't been released in a while and it's missing from the version currently on rubygems. I'm working on getting a new release cut.

**Comment by eheydrick** [comment] 2017-05-16 06:01
1.0.0 is live on rubygems.

**Closed as completed by eheydrick** 2017-05-16 06:01 UTC
